theme: jekyll-theme-cayman
title: Athindran Ramesh Kumar
description: Project Associate at RISE lab, CS Department, IIT Madras and Research Engineer at Center of Excellence in Wireless Technology, IIT Madras
